
package com.zkw.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyWebService", targetNamespace = "http://localhost/client", wsdlLocation = "http://localhost:8080/MyWebService?wsdl")
public class MyWebService
    extends Service
{

    private final static URL MYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWEBSERVICE_EXCEPTION;
    private final static QName MYWEBSERVICE_QNAME = new QName("http://localhost/client", "MyWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MyWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWEBSERVICE_WSDL_LOCATION = url;
        MYWEBSERVICE_EXCEPTION = e;
    }

    public MyWebService() {
        super(__getWsdlLocation(), MYWEBSERVICE_QNAME);
    }

    public MyWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYWEBSERVICE_QNAME, features);
    }

    public MyWebService(URL wsdlLocation) {
        super(wsdlLocation, MYWEBSERVICE_QNAME);
    }

    public MyWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYWEBSERVICE_QNAME, features);
    }

    public MyWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyTestWS
     */
    @WebEndpoint(name = "MyTestWSPort")
    public MyTestWS getMyTestWSPort() {
        return super.getPort(new QName("http://localhost/client", "MyTestWSPort"), MyTestWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyTestWS
     */
    @WebEndpoint(name = "MyTestWSPort")
    public MyTestWS getMyTestWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/client", "MyTestWSPort"), MyTestWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYWEBSERVICE_EXCEPTION!= null) {
            throw MYWEBSERVICE_EXCEPTION;
        }
        return MYWEBSERVICE_WSDL_LOCATION;
    }

}
